// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_exchange.proto

#include "key_exchange.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ee2e {
PROTOBUF_CONSTEXPR KeyExchangeRequest::KeyExchangeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_info_)*/nullptr
  , /*decltype(_impl_.key_exchange_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KeyExchangeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeyExchangeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyExchangeRequestDefaultTypeInternal() {}
  union {
    KeyExchangeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyExchangeRequestDefaultTypeInternal _KeyExchangeRequest_default_instance_;
PROTOBUF_CONSTEXPR EncryptedRequest::EncryptedRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.token_)*/nullptr
  , /*decltype(_impl_.ciphertext_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EncryptedRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncryptedRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncryptedRequestDefaultTypeInternal() {}
  union {
    EncryptedRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncryptedRequestDefaultTypeInternal _EncryptedRequest_default_instance_;
PROTOBUF_CONSTEXPR KeyInfo::KeyInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.salt_32bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ec_public_key_65bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KeyInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeyInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyInfoDefaultTypeInternal() {}
  union {
    KeyInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyInfoDefaultTypeInternal _KeyInfo_default_instance_;
PROTOBUF_CONSTEXPR Token::Token(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.salt_3bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.hmac_3bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TokenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TokenDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TokenDefaultTypeInternal() {}
  union {
    Token _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TokenDefaultTypeInternal _Token_default_instance_;
PROTOBUF_CONSTEXPR Ciphertext::Ciphertext(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.aes_iv_12bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ciphertext_nbytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.aes_tag_16bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cipher_version_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CiphertextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CiphertextDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CiphertextDefaultTypeInternal() {}
  union {
    Ciphertext _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CiphertextDefaultTypeInternal _Ciphertext_default_instance_;
}  // namespace ee2e
static ::_pb::Metadata file_level_metadata_key_5fexchange_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_key_5fexchange_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_key_5fexchange_2eproto = nullptr;

const uint32_t TableStruct_key_5fexchange_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ee2e::KeyExchangeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ee2e::KeyExchangeRequest, _impl_.key_exchange_type_),
  PROTOBUF_FIELD_OFFSET(::ee2e::KeyExchangeRequest, _impl_.key_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ee2e::EncryptedRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ee2e::EncryptedRequest, _impl_.token_),
  PROTOBUF_FIELD_OFFSET(::ee2e::EncryptedRequest, _impl_.ciphertext_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ee2e::KeyInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ee2e::KeyInfo, _impl_.salt_32bytes_),
  PROTOBUF_FIELD_OFFSET(::ee2e::KeyInfo, _impl_.ec_public_key_65bytes_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ee2e::Token, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ee2e::Token, _impl_.salt_3bytes_),
  PROTOBUF_FIELD_OFFSET(::ee2e::Token, _impl_.hmac_3bytes_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ee2e::Ciphertext, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ee2e::Ciphertext, _impl_.cipher_version_),
  PROTOBUF_FIELD_OFFSET(::ee2e::Ciphertext, _impl_.aes_iv_12bytes_),
  PROTOBUF_FIELD_OFFSET(::ee2e::Ciphertext, _impl_.ciphertext_nbytes_),
  PROTOBUF_FIELD_OFFSET(::ee2e::Ciphertext, _impl_.aes_tag_16bytes_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ee2e::KeyExchangeRequest)},
  { 8, -1, -1, sizeof(::ee2e::EncryptedRequest)},
  { 16, -1, -1, sizeof(::ee2e::KeyInfo)},
  { 24, -1, -1, sizeof(::ee2e::Token)},
  { 32, -1, -1, sizeof(::ee2e::Ciphertext)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ee2e::_KeyExchangeRequest_default_instance_._instance,
  &::ee2e::_EncryptedRequest_default_instance_._instance,
  &::ee2e::_KeyInfo_default_instance_._instance,
  &::ee2e::_Token_default_instance_._instance,
  &::ee2e::_Ciphertext_default_instance_._instance,
};

const char descriptor_table_protodef_key_5fexchange_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022key_exchange.proto\022\004ee2e\"g\n\022KeyExchang"
  "eRequest\0220\n\021key_exchange_type\030\001 \001(\0162\025.ee"
  "2e.KeyExchangeType\022\037\n\010key_info\030\002 \001(\0132\r.e"
  "e2e.KeyInfo\"T\n\020EncryptedRequest\022\032\n\005token"
  "\030\001 \001(\0132\013.ee2e.Token\022$\n\nciphertext\030\002 \001(\0132"
  "\020.ee2e.Ciphertext\">\n\007KeyInfo\022\024\n\014salt_32b"
  "ytes\030\001 \001(\t\022\035\n\025ec_public_key_65bytes\030\002 \001("
  "\t\"1\n\005Token\022\023\n\013salt_3bytes\030\001 \001(\t\022\023\n\013hmac_"
  "3bytes\030\002 \001(\t\"p\n\nCiphertext\022\026\n\016cipher_ver"
  "sion\030\001 \001(\005\022\026\n\016aes_iv_12bytes\030\002 \001(\t\022\031\n\021ci"
  "phertext_nbytes\030\003 \001(\t\022\027\n\017aes_tag_16bytes"
  "\030\004 \001(\t*a\n\017KeyExchangeType\022\030\n\024UNKNOWN_REQ"
  "UEST_TYPE\020\000\022\031\n\025KEY_EXCHANGE_INITIATE\020\001\022\031"
  "\n\025KEY_EXCHANGE_FINALIZE\020\002*:\n\007MESSAGE\022\013\n\007"
  "UNKNOWN\020\000\022\020\n\010INITIATE\020\261\357\361\334\003\022\020\n\010FINALIZE\020"
  "\301\321\335\271\007b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_key_5fexchange_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_key_5fexchange_2eproto = {
    false, false, 613, descriptor_table_protodef_key_5fexchange_2eproto,
    "key_exchange.proto",
    &descriptor_table_key_5fexchange_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_key_5fexchange_2eproto::offsets,
    file_level_metadata_key_5fexchange_2eproto, file_level_enum_descriptors_key_5fexchange_2eproto,
    file_level_service_descriptors_key_5fexchange_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_key_5fexchange_2eproto_getter() {
  return &descriptor_table_key_5fexchange_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_key_5fexchange_2eproto(&descriptor_table_key_5fexchange_2eproto);
namespace ee2e {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* KeyExchangeType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_key_5fexchange_2eproto);
  return file_level_enum_descriptors_key_5fexchange_2eproto[0];
}
bool KeyExchangeType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MESSAGE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_key_5fexchange_2eproto);
  return file_level_enum_descriptors_key_5fexchange_2eproto[1];
}
bool MESSAGE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000110001:
    case 2000120001:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class KeyExchangeRequest::_Internal {
 public:
  static const ::ee2e::KeyInfo& key_info(const KeyExchangeRequest* msg);
};

const ::ee2e::KeyInfo&
KeyExchangeRequest::_Internal::key_info(const KeyExchangeRequest* msg) {
  return *msg->_impl_.key_info_;
}
KeyExchangeRequest::KeyExchangeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ee2e.KeyExchangeRequest)
}
KeyExchangeRequest::KeyExchangeRequest(const KeyExchangeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KeyExchangeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_info_){nullptr}
    , decltype(_impl_.key_exchange_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_key_info()) {
    _this->_impl_.key_info_ = new ::ee2e::KeyInfo(*from._impl_.key_info_);
  }
  _this->_impl_.key_exchange_type_ = from._impl_.key_exchange_type_;
  // @@protoc_insertion_point(copy_constructor:ee2e.KeyExchangeRequest)
}

inline void KeyExchangeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_info_){nullptr}
    , decltype(_impl_.key_exchange_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

KeyExchangeRequest::~KeyExchangeRequest() {
  // @@protoc_insertion_point(destructor:ee2e.KeyExchangeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KeyExchangeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.key_info_;
}

void KeyExchangeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KeyExchangeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ee2e.KeyExchangeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.key_info_ != nullptr) {
    delete _impl_.key_info_;
  }
  _impl_.key_info_ = nullptr;
  _impl_.key_exchange_type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KeyExchangeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ee2e.KeyExchangeType key_exchange_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_key_exchange_type(static_cast<::ee2e::KeyExchangeType>(val));
        } else
          goto handle_unusual;
        continue;
      // .ee2e.KeyInfo key_info = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_key_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* KeyExchangeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ee2e.KeyExchangeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ee2e.KeyExchangeType key_exchange_type = 1;
  if (this->_internal_key_exchange_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_key_exchange_type(), target);
  }

  // .ee2e.KeyInfo key_info = 2;
  if (this->_internal_has_key_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::key_info(this),
        _Internal::key_info(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ee2e.KeyExchangeRequest)
  return target;
}

size_t KeyExchangeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ee2e.KeyExchangeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ee2e.KeyInfo key_info = 2;
  if (this->_internal_has_key_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.key_info_);
  }

  // .ee2e.KeyExchangeType key_exchange_type = 1;
  if (this->_internal_key_exchange_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_key_exchange_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KeyExchangeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    KeyExchangeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KeyExchangeRequest::GetClassData() const { return &_class_data_; }


void KeyExchangeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<KeyExchangeRequest*>(&to_msg);
  auto& from = static_cast<const KeyExchangeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ee2e.KeyExchangeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_key_info()) {
    _this->_internal_mutable_key_info()->::ee2e::KeyInfo::MergeFrom(
        from._internal_key_info());
  }
  if (from._internal_key_exchange_type() != 0) {
    _this->_internal_set_key_exchange_type(from._internal_key_exchange_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KeyExchangeRequest::CopyFrom(const KeyExchangeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ee2e.KeyExchangeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyExchangeRequest::IsInitialized() const {
  return true;
}

void KeyExchangeRequest::InternalSwap(KeyExchangeRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KeyExchangeRequest, _impl_.key_exchange_type_)
      + sizeof(KeyExchangeRequest::_impl_.key_exchange_type_)
      - PROTOBUF_FIELD_OFFSET(KeyExchangeRequest, _impl_.key_info_)>(
          reinterpret_cast<char*>(&_impl_.key_info_),
          reinterpret_cast<char*>(&other->_impl_.key_info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata KeyExchangeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_key_5fexchange_2eproto_getter, &descriptor_table_key_5fexchange_2eproto_once,
      file_level_metadata_key_5fexchange_2eproto[0]);
}

// ===================================================================

class EncryptedRequest::_Internal {
 public:
  static const ::ee2e::Token& token(const EncryptedRequest* msg);
  static const ::ee2e::Ciphertext& ciphertext(const EncryptedRequest* msg);
};

const ::ee2e::Token&
EncryptedRequest::_Internal::token(const EncryptedRequest* msg) {
  return *msg->_impl_.token_;
}
const ::ee2e::Ciphertext&
EncryptedRequest::_Internal::ciphertext(const EncryptedRequest* msg) {
  return *msg->_impl_.ciphertext_;
}
EncryptedRequest::EncryptedRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ee2e.EncryptedRequest)
}
EncryptedRequest::EncryptedRequest(const EncryptedRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EncryptedRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){nullptr}
    , decltype(_impl_.ciphertext_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_token()) {
    _this->_impl_.token_ = new ::ee2e::Token(*from._impl_.token_);
  }
  if (from._internal_has_ciphertext()) {
    _this->_impl_.ciphertext_ = new ::ee2e::Ciphertext(*from._impl_.ciphertext_);
  }
  // @@protoc_insertion_point(copy_constructor:ee2e.EncryptedRequest)
}

inline void EncryptedRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){nullptr}
    , decltype(_impl_.ciphertext_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

EncryptedRequest::~EncryptedRequest() {
  // @@protoc_insertion_point(destructor:ee2e.EncryptedRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EncryptedRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.token_;
  if (this != internal_default_instance()) delete _impl_.ciphertext_;
}

void EncryptedRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EncryptedRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ee2e.EncryptedRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.token_ != nullptr) {
    delete _impl_.token_;
  }
  _impl_.token_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.ciphertext_ != nullptr) {
    delete _impl_.ciphertext_;
  }
  _impl_.ciphertext_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EncryptedRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ee2e.Token token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_token(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ee2e.Ciphertext ciphertext = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_ciphertext(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EncryptedRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ee2e.EncryptedRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ee2e.Token token = 1;
  if (this->_internal_has_token()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::token(this),
        _Internal::token(this).GetCachedSize(), target, stream);
  }

  // .ee2e.Ciphertext ciphertext = 2;
  if (this->_internal_has_ciphertext()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::ciphertext(this),
        _Internal::ciphertext(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ee2e.EncryptedRequest)
  return target;
}

size_t EncryptedRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ee2e.EncryptedRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ee2e.Token token = 1;
  if (this->_internal_has_token()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.token_);
  }

  // .ee2e.Ciphertext ciphertext = 2;
  if (this->_internal_has_ciphertext()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ciphertext_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EncryptedRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EncryptedRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EncryptedRequest::GetClassData() const { return &_class_data_; }


void EncryptedRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EncryptedRequest*>(&to_msg);
  auto& from = static_cast<const EncryptedRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ee2e.EncryptedRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_token()) {
    _this->_internal_mutable_token()->::ee2e::Token::MergeFrom(
        from._internal_token());
  }
  if (from._internal_has_ciphertext()) {
    _this->_internal_mutable_ciphertext()->::ee2e::Ciphertext::MergeFrom(
        from._internal_ciphertext());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EncryptedRequest::CopyFrom(const EncryptedRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ee2e.EncryptedRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EncryptedRequest::IsInitialized() const {
  return true;
}

void EncryptedRequest::InternalSwap(EncryptedRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EncryptedRequest, _impl_.ciphertext_)
      + sizeof(EncryptedRequest::_impl_.ciphertext_)
      - PROTOBUF_FIELD_OFFSET(EncryptedRequest, _impl_.token_)>(
          reinterpret_cast<char*>(&_impl_.token_),
          reinterpret_cast<char*>(&other->_impl_.token_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EncryptedRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_key_5fexchange_2eproto_getter, &descriptor_table_key_5fexchange_2eproto_once,
      file_level_metadata_key_5fexchange_2eproto[1]);
}

// ===================================================================

class KeyInfo::_Internal {
 public:
};

KeyInfo::KeyInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ee2e.KeyInfo)
}
KeyInfo::KeyInfo(const KeyInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KeyInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.salt_32bytes_){}
    , decltype(_impl_.ec_public_key_65bytes_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.salt_32bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.salt_32bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_salt_32bytes().empty()) {
    _this->_impl_.salt_32bytes_.Set(from._internal_salt_32bytes(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ec_public_key_65bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ec_public_key_65bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ec_public_key_65bytes().empty()) {
    _this->_impl_.ec_public_key_65bytes_.Set(from._internal_ec_public_key_65bytes(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ee2e.KeyInfo)
}

inline void KeyInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.salt_32bytes_){}
    , decltype(_impl_.ec_public_key_65bytes_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.salt_32bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.salt_32bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ec_public_key_65bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ec_public_key_65bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

KeyInfo::~KeyInfo() {
  // @@protoc_insertion_point(destructor:ee2e.KeyInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KeyInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.salt_32bytes_.Destroy();
  _impl_.ec_public_key_65bytes_.Destroy();
}

void KeyInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KeyInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ee2e.KeyInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.salt_32bytes_.ClearToEmpty();
  _impl_.ec_public_key_65bytes_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KeyInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string salt_32bytes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_salt_32bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ee2e.KeyInfo.salt_32bytes"));
        } else
          goto handle_unusual;
        continue;
      // string ec_public_key_65bytes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_ec_public_key_65bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ee2e.KeyInfo.ec_public_key_65bytes"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* KeyInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ee2e.KeyInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string salt_32bytes = 1;
  if (!this->_internal_salt_32bytes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_salt_32bytes().data(), static_cast<int>(this->_internal_salt_32bytes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ee2e.KeyInfo.salt_32bytes");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_salt_32bytes(), target);
  }

  // string ec_public_key_65bytes = 2;
  if (!this->_internal_ec_public_key_65bytes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ec_public_key_65bytes().data(), static_cast<int>(this->_internal_ec_public_key_65bytes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ee2e.KeyInfo.ec_public_key_65bytes");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_ec_public_key_65bytes(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ee2e.KeyInfo)
  return target;
}

size_t KeyInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ee2e.KeyInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string salt_32bytes = 1;
  if (!this->_internal_salt_32bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_salt_32bytes());
  }

  // string ec_public_key_65bytes = 2;
  if (!this->_internal_ec_public_key_65bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ec_public_key_65bytes());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KeyInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    KeyInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KeyInfo::GetClassData() const { return &_class_data_; }


void KeyInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<KeyInfo*>(&to_msg);
  auto& from = static_cast<const KeyInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ee2e.KeyInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_salt_32bytes().empty()) {
    _this->_internal_set_salt_32bytes(from._internal_salt_32bytes());
  }
  if (!from._internal_ec_public_key_65bytes().empty()) {
    _this->_internal_set_ec_public_key_65bytes(from._internal_ec_public_key_65bytes());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KeyInfo::CopyFrom(const KeyInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ee2e.KeyInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyInfo::IsInitialized() const {
  return true;
}

void KeyInfo::InternalSwap(KeyInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.salt_32bytes_, lhs_arena,
      &other->_impl_.salt_32bytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ec_public_key_65bytes_, lhs_arena,
      &other->_impl_.ec_public_key_65bytes_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata KeyInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_key_5fexchange_2eproto_getter, &descriptor_table_key_5fexchange_2eproto_once,
      file_level_metadata_key_5fexchange_2eproto[2]);
}

// ===================================================================

class Token::_Internal {
 public:
};

Token::Token(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ee2e.Token)
}
Token::Token(const Token& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Token* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.salt_3bytes_){}
    , decltype(_impl_.hmac_3bytes_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.salt_3bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.salt_3bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_salt_3bytes().empty()) {
    _this->_impl_.salt_3bytes_.Set(from._internal_salt_3bytes(), 
      _this->GetArenaForAllocation());
  }
  _impl_.hmac_3bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hmac_3bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hmac_3bytes().empty()) {
    _this->_impl_.hmac_3bytes_.Set(from._internal_hmac_3bytes(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ee2e.Token)
}

inline void Token::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.salt_3bytes_){}
    , decltype(_impl_.hmac_3bytes_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.salt_3bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.salt_3bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.hmac_3bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hmac_3bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Token::~Token() {
  // @@protoc_insertion_point(destructor:ee2e.Token)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Token::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.salt_3bytes_.Destroy();
  _impl_.hmac_3bytes_.Destroy();
}

void Token::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Token::Clear() {
// @@protoc_insertion_point(message_clear_start:ee2e.Token)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.salt_3bytes_.ClearToEmpty();
  _impl_.hmac_3bytes_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Token::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string salt_3bytes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_salt_3bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ee2e.Token.salt_3bytes"));
        } else
          goto handle_unusual;
        continue;
      // string hmac_3bytes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_hmac_3bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ee2e.Token.hmac_3bytes"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Token::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ee2e.Token)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string salt_3bytes = 1;
  if (!this->_internal_salt_3bytes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_salt_3bytes().data(), static_cast<int>(this->_internal_salt_3bytes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ee2e.Token.salt_3bytes");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_salt_3bytes(), target);
  }

  // string hmac_3bytes = 2;
  if (!this->_internal_hmac_3bytes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hmac_3bytes().data(), static_cast<int>(this->_internal_hmac_3bytes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ee2e.Token.hmac_3bytes");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_hmac_3bytes(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ee2e.Token)
  return target;
}

size_t Token::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ee2e.Token)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string salt_3bytes = 1;
  if (!this->_internal_salt_3bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_salt_3bytes());
  }

  // string hmac_3bytes = 2;
  if (!this->_internal_hmac_3bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hmac_3bytes());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Token::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Token::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Token::GetClassData() const { return &_class_data_; }


void Token::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Token*>(&to_msg);
  auto& from = static_cast<const Token&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ee2e.Token)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_salt_3bytes().empty()) {
    _this->_internal_set_salt_3bytes(from._internal_salt_3bytes());
  }
  if (!from._internal_hmac_3bytes().empty()) {
    _this->_internal_set_hmac_3bytes(from._internal_hmac_3bytes());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Token::CopyFrom(const Token& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ee2e.Token)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Token::IsInitialized() const {
  return true;
}

void Token::InternalSwap(Token* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.salt_3bytes_, lhs_arena,
      &other->_impl_.salt_3bytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hmac_3bytes_, lhs_arena,
      &other->_impl_.hmac_3bytes_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Token::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_key_5fexchange_2eproto_getter, &descriptor_table_key_5fexchange_2eproto_once,
      file_level_metadata_key_5fexchange_2eproto[3]);
}

// ===================================================================

class Ciphertext::_Internal {
 public:
};

Ciphertext::Ciphertext(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ee2e.Ciphertext)
}
Ciphertext::Ciphertext(const Ciphertext& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Ciphertext* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.aes_iv_12bytes_){}
    , decltype(_impl_.ciphertext_nbytes_){}
    , decltype(_impl_.aes_tag_16bytes_){}
    , decltype(_impl_.cipher_version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.aes_iv_12bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aes_iv_12bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_aes_iv_12bytes().empty()) {
    _this->_impl_.aes_iv_12bytes_.Set(from._internal_aes_iv_12bytes(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ciphertext_nbytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ciphertext_nbytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ciphertext_nbytes().empty()) {
    _this->_impl_.ciphertext_nbytes_.Set(from._internal_ciphertext_nbytes(), 
      _this->GetArenaForAllocation());
  }
  _impl_.aes_tag_16bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aes_tag_16bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_aes_tag_16bytes().empty()) {
    _this->_impl_.aes_tag_16bytes_.Set(from._internal_aes_tag_16bytes(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.cipher_version_ = from._impl_.cipher_version_;
  // @@protoc_insertion_point(copy_constructor:ee2e.Ciphertext)
}

inline void Ciphertext::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.aes_iv_12bytes_){}
    , decltype(_impl_.ciphertext_nbytes_){}
    , decltype(_impl_.aes_tag_16bytes_){}
    , decltype(_impl_.cipher_version_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.aes_iv_12bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aes_iv_12bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ciphertext_nbytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ciphertext_nbytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.aes_tag_16bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aes_tag_16bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Ciphertext::~Ciphertext() {
  // @@protoc_insertion_point(destructor:ee2e.Ciphertext)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Ciphertext::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.aes_iv_12bytes_.Destroy();
  _impl_.ciphertext_nbytes_.Destroy();
  _impl_.aes_tag_16bytes_.Destroy();
}

void Ciphertext::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Ciphertext::Clear() {
// @@protoc_insertion_point(message_clear_start:ee2e.Ciphertext)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.aes_iv_12bytes_.ClearToEmpty();
  _impl_.ciphertext_nbytes_.ClearToEmpty();
  _impl_.aes_tag_16bytes_.ClearToEmpty();
  _impl_.cipher_version_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Ciphertext::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 cipher_version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.cipher_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string aes_iv_12bytes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_aes_iv_12bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ee2e.Ciphertext.aes_iv_12bytes"));
        } else
          goto handle_unusual;
        continue;
      // string ciphertext_nbytes = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_ciphertext_nbytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ee2e.Ciphertext.ciphertext_nbytes"));
        } else
          goto handle_unusual;
        continue;
      // string aes_tag_16bytes = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_aes_tag_16bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ee2e.Ciphertext.aes_tag_16bytes"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ciphertext::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ee2e.Ciphertext)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 cipher_version = 1;
  if (this->_internal_cipher_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_cipher_version(), target);
  }

  // string aes_iv_12bytes = 2;
  if (!this->_internal_aes_iv_12bytes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_aes_iv_12bytes().data(), static_cast<int>(this->_internal_aes_iv_12bytes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ee2e.Ciphertext.aes_iv_12bytes");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_aes_iv_12bytes(), target);
  }

  // string ciphertext_nbytes = 3;
  if (!this->_internal_ciphertext_nbytes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ciphertext_nbytes().data(), static_cast<int>(this->_internal_ciphertext_nbytes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ee2e.Ciphertext.ciphertext_nbytes");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_ciphertext_nbytes(), target);
  }

  // string aes_tag_16bytes = 4;
  if (!this->_internal_aes_tag_16bytes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_aes_tag_16bytes().data(), static_cast<int>(this->_internal_aes_tag_16bytes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ee2e.Ciphertext.aes_tag_16bytes");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_aes_tag_16bytes(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ee2e.Ciphertext)
  return target;
}

size_t Ciphertext::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ee2e.Ciphertext)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string aes_iv_12bytes = 2;
  if (!this->_internal_aes_iv_12bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_aes_iv_12bytes());
  }

  // string ciphertext_nbytes = 3;
  if (!this->_internal_ciphertext_nbytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ciphertext_nbytes());
  }

  // string aes_tag_16bytes = 4;
  if (!this->_internal_aes_tag_16bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_aes_tag_16bytes());
  }

  // int32 cipher_version = 1;
  if (this->_internal_cipher_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cipher_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Ciphertext::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Ciphertext::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Ciphertext::GetClassData() const { return &_class_data_; }


void Ciphertext::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Ciphertext*>(&to_msg);
  auto& from = static_cast<const Ciphertext&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ee2e.Ciphertext)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_aes_iv_12bytes().empty()) {
    _this->_internal_set_aes_iv_12bytes(from._internal_aes_iv_12bytes());
  }
  if (!from._internal_ciphertext_nbytes().empty()) {
    _this->_internal_set_ciphertext_nbytes(from._internal_ciphertext_nbytes());
  }
  if (!from._internal_aes_tag_16bytes().empty()) {
    _this->_internal_set_aes_tag_16bytes(from._internal_aes_tag_16bytes());
  }
  if (from._internal_cipher_version() != 0) {
    _this->_internal_set_cipher_version(from._internal_cipher_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Ciphertext::CopyFrom(const Ciphertext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ee2e.Ciphertext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ciphertext::IsInitialized() const {
  return true;
}

void Ciphertext::InternalSwap(Ciphertext* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.aes_iv_12bytes_, lhs_arena,
      &other->_impl_.aes_iv_12bytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ciphertext_nbytes_, lhs_arena,
      &other->_impl_.ciphertext_nbytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.aes_tag_16bytes_, lhs_arena,
      &other->_impl_.aes_tag_16bytes_, rhs_arena
  );
  swap(_impl_.cipher_version_, other->_impl_.cipher_version_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Ciphertext::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_key_5fexchange_2eproto_getter, &descriptor_table_key_5fexchange_2eproto_once,
      file_level_metadata_key_5fexchange_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ee2e
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ee2e::KeyExchangeRequest*
Arena::CreateMaybeMessage< ::ee2e::KeyExchangeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ee2e::KeyExchangeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ee2e::EncryptedRequest*
Arena::CreateMaybeMessage< ::ee2e::EncryptedRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ee2e::EncryptedRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ee2e::KeyInfo*
Arena::CreateMaybeMessage< ::ee2e::KeyInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ee2e::KeyInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::ee2e::Token*
Arena::CreateMaybeMessage< ::ee2e::Token >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ee2e::Token >(arena);
}
template<> PROTOBUF_NOINLINE ::ee2e::Ciphertext*
Arena::CreateMaybeMessage< ::ee2e::Ciphertext >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ee2e::Ciphertext >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
